### PR TITLE
Update sample_config.py

### PR DESCRIPTION
**Pull request by REQUESTMOVIES-FAMILY**

### CODE REVIEW

**Comment by Godzilla-0** [comment]
@REQUESTMOVIES-FAMILY Lol wtf?

**Comment by FtSasaki** [comment]
@REQUESTMOVIES-FAMILY hunn?

**Comment by FtSasaki** [comment]
kindely do these changes on ur own bot not in Senku!
First Fork then make changes

**Comment by Godzilla-0** [comment]
@FtSasaki 😂😂😂

**Comment by Uday0011** [comment]
@FtSasaki 😂😂

**Pull request closed without merging**
